version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 16"
      - n 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Test started on `date`
      - npm test -- --watchAll=false
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - src/index.js
    - src/app.js
    - package.json
    - node_modules/**/*

