version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
      - echo Build started on `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
  # Include only the files required for your application to run.
  artifacts:
    files:
      - src/index.js
      - src/app.js
      - package.json
      - node_modules/**/*

